docker pull microsoft/dotnet-samples:dotnetapp-nanoserver-sac2016
docker pull microsoft/nanoserver:sac2016
docker pull microsoft/iis:nanoserver-sac2016
docker pull microsoft/mssql-server-windows-express
docker pull microsoft/windowsservercore
docker pull microsoft/dotnet-framework:4.7.2-sdk-windowsservercore-ltsc2016
docker pull microsoft/aspnet:4.7.2-windowsservercore-ltsc2016
docker pull dockersamples/mta-dev-web-builder:4.7.1
docker pull microsoft/aspnet:4.7.1-windowsservercore-ltsc2016
docker pull microsoft/bcsandbox:us
docker pull mcr.microsoft.com/businesscentral/onprem
docker pull microsoft/dynamics-nav:2018-gb